defaults:
  - algorithm: wm_rnd
  - env: harvest_common_open
  - model@model.encoder: encoder
  - model@model.decoder: decoder
  - _self_

checkpoint_dir: null
checkpoint_step: null
# Relative paths are resolved under checkpoint_dir.
output_dir: ""
max_steps: 1000
render: true
gif_fps: 12
num_episodes: 1
deterministic: false
xla_python_client_mem_fraction: 0.4

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
