defaults:
  - algorithm: mappo
  - env: clean_up
  - model@model.encoder: encoder
  - model@model.decoder: decoder
  - wandb: default
  - _self_

seed: 0
dry_run: false
xla_python_client_mem_fraction: 0.9


hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
    env_set:
      PYTHONPATH: .
