defaults:
  - algorithm: ippo
  - env: clean_up
  - _self_

independent_policy: null
independent_reward: null
seed: 0
dry_run: false

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
