name: ippo

NUM_ENVS: 128
NUM_STEPS: 1000
TOTAL_TIMESTEPS: 100000
UPDATE_EPOCHS: 2
NUM_MINIBATCHES: 500
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
LR: 0.0005
ANNEAL_LR: false
PARAMETER_SHARING: true
ACTIVATION: relu

MLP_HIDDEN_SIZES: [64, 64]
CNN_CHANNELS: [32, 32, 32]
CNN_KERNEL_SIZES:
  - [5, 5]
  - [3, 3]
  - [3, 3]
CNN_DENSE_SIZE: 64
