name: ippo

independent_policy: null
independent_reward: null

NUM_ENVS: 10
NUM_STEPS: 1000
TOTAL_TIMESTEPS: 1000000
UPDATE_EPOCHS: 2
NUM_MINIBATCHES: 500
GAMMA: 0.999
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
LR: 0.0005
ANNEAL_LR: false
PARAMETER_SHARING: true

CHECKPOINT_DIR: ippo
CHECKPOINT_EVERY: 100
CHECKPOINT_KEEP: 3

INIT_CHECKPOINT_DIR: null
INIT_CHECKPOINT_STEP: null
INIT_AGENT_SOURCE_IDS: null
