name: mappo

NUM_ENVS: 32
NUM_STEPS: 128
TOTAL_TIMESTEPS: 10000000
UPDATE_EPOCHS: 2
NUM_MINIBATCHES: 4
GAMMA: 0.999
GAE_LAMBDA: 0.95
CLIP_EPS: 0.1
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
LR: 0.0005
ANNEAL_LR: false

CHECKPOINT_DIR: mappo
CHECKPOINT_EVERY: 1000
CHECKPOINT_KEEP: 3
