name: mappo

NUM_ENVS: 32
NUM_STEPS: 16
TOTAL_TIMESTEPS: 1000000
UPDATE_EPOCHS: 5
NUM_MINIBATCHES: 2
GAMMA: 0.999
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.001
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
LR: 0.0001
ANNEAL_LR: true

CHECKPOINT_DIR: mappo
CHECKPOINT_EVERY: 10
CHECKPOINT_KEEP: 3
