name: wm_rnd

NUM_ENVS: 16
NUM_STEPS: 64
TOTAL_TIMESTEPS: 1000000
UPDATE_EPOCHS: 5
NUM_MINIBATCHES: 4 # Batch size = 16 * 128 / 4 = 512
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 1.0
LR: 0.0005
ANNEAL_LR: false

# Novelty & World Model Specific
INTRINSIC_COEF: 5
RND_LR: 0.0001
WM_LR: 0.0001
IMAGINATION_STEPS: 1024
# IMAGINATION_EPOCHS: 2
IMAGINATION_COEF: 0.01
RND_SHARED: false
WM_JOINT_ACTION: true
SYMMETRY_RATIO: 1.0

CHECKPOINT_DIR: wm_rnd
CHECKPOINT_EVERY: 5
CHECKPOINT_KEEP: 3
