env_name: coin_game
env_kwargs:
  num_agents: 2
  num_inner_steps: 1000
  num_outer_steps: 1
  shared_rewards: true
  regrow_rate: 0.0005
  payoff_matrix:
    - [1, 1, -2]
    - [1, 1, -2]
  cnn: true
  jit: true
wandb:
  project: socialjax_components_coin_game
  tags:
    - coin_game
