env_name: coop_mining
env_kwargs:
  num_agents: 4
  num_inner_steps: 1000
  num_outer_steps: 1
  shared_rewards: true
  max_miners: 4
  min_gold_miners: 2
  mining_range: 3
  reward_iron: 1.0
  reward_gold: 8.0
  gold_mining_window: 3
  regrowth_prob_iron: 0.0002
  regrowth_prob_gold: 0.00008
  cnn: true
  jit: true
wandb:
  project: socialjax_components_coop_mining
  tags:
    - coop_mining
