env_name: pd_arena
env_kwargs:
  num_agents: 7
  num_inner_steps: 1000
  num_outer_steps: 1
  shared_rewards: true
  cnn: true
  jit: true
wandb:
  project: socialjax_components_pd_arena
  tags:
    - pd_arena
