"LR": 0.0005
"NUM_ENVS": 256
"NUM_STEPS": 1000
"TOTAL_TIMESTEPS": 3e8
"UPDATE_EPOCHS": 2
"NUM_MINIBATCHES": 500
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "clean_up"
"REW_SHAPING_HORIZON": 2.5e6
"SHAPING_BEGIN": 1e6
"ENV_KWARGS": 
  "num_agents" : 7
  "num_inner_steps" : 1000
  "shared_rewards" : False
  "cnn" : True
  "jit" : True
  
"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 1
"TUNE": True

"REWARD": "individual"
"GIF_NUM_FRAMES": 250
"PARAMETER_SHARING": True

# Model-Based Params
"MODEL_LR": 0.001
"DREAM_HORIZON": 5
"DREAM_RATIO": 0.5
"MODEL_COEF": 1.0

# WandB Params
"ENTITY": ""
"PROJECT": "socialjax"
"WANDB_MODE" : "online"
"WANDB_TAGS":
  - INDIVIDUAL_REWARD
  - MB_IPPO
